package com.amazonaws.lambda.entities;

import java.time.LocalDate;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedDefault;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;

@DynamoDBTable(tableName = "ClientData")
public class Client {
	
	private String id;
	private String email_id;
	private String client_name;
	private String company_name;
	private String phone_no;
	private String status;
	private String deleteBy;
	private LocalDate time;
	

	@DynamoDBAttribute(attributeName = "id")
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBHashKey(attributeName = "email_id")
	public String getEmail_id() {
		return email_id;
	}
	public void setEmail_id(String email_id) {
		this.email_id = email_id;
	}
	
	@DynamoDBAttribute(attributeName = "client_name")
	public String getClient_name() {
		return client_name;
	}
	public void setClient_name(String client_name) {
		this.client_name = client_name;
	}
	
	@DynamoDBAttribute(attributeName = "company_name")
	public String getCompany_name() {
		return company_name;
	}
	public void setCompany_name(String company_name) {
		this.company_name = company_name;
	}
	
	@DynamoDBAttribute(attributeName = "phone_no")
	public String getPhone_no() {
		return phone_no;
	}
	public void setPhone_no(String phone_no) {
		this.phone_no = phone_no;
	}
	
	@DynamoDBAttribute(attributeName = "status")
	@DynamoDBAutoGeneratedDefault(value = "Active")
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	
	@DynamoDBAttribute(attributeName = "deleteBy")
	@DynamoDBAutoGeneratedDefault(value = "null")
	public String getDeleteBy() {
		return deleteBy;
	}
	public void setDeleteBy(String deleteBy) {
		this.deleteBy = deleteBy;
	}
	
	@DynamoDBAttribute(attributeName = "time")
	@DynamoDBTyped(DynamoDBAttributeType.S)
	public LocalDate getTime() {
		return time;
	}
	public void setTime(LocalDate time) {
		this.time = time;
	}
	
	
	@Override
	public String toString() {
		return "Client [id=" + id + ", email_id=" + email_id + ", client_name=" + client_name + ", company_name="
				+ company_name + ", phone_no=" + phone_no + ", status=" + status + ", deleteBy=" + deleteBy + ", time="
				+ time + "]";
	}
	
	
	
	
	
	
}
